name: Node.js CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    # See: https://github.com/actions/setup-node/issues/480
    - run: corepack enable
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.13.2
    - run: yarn install --immutable
    - run: yarn test
